---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 2fauth

commonLabels:
  app.kubernetes.io/name: 2fauth

resources:
  - persistent_volumes.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: 2fauth-config
    envs:
      - config.env
