---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 2fauth-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
